## **Predicting Laptop Prices: From Data Analysis to Streamlit App Deployment 🖥️💰🔮**

**Introduction:**
In this Kaggle notebook, I embarked on a journey to predict laptop prices using a dataset containing information about various laptops. My goal was to develop a predictive model capable of estimating laptop prices accurately based on their specifications. Along the way, I explored data preprocessing techniques, evaluated multiple machine learning models, and eventually deployed a Streamlit web application for real-time price prediction.

**Data Exploration and Preprocessing:**
- I began by loading the dataset and performing exploratory data analysis to understand its structure and characteristics.
- Identified missing values, outliers, and inconsistencies in the data.
- Conducted data preprocessing steps such as handling missing values, encoding categorical variables, and scaling numerical features.
- Explored the distribution of the target variable (laptop prices) and checked for skewness.

**Model Training and Evaluation:**
- Split the dataset into training and testing sets.
- Evaluated various machine learning models including Random Forest Regressor, Gradient Boosting Regressor, XGBoost Regressor, and others.
- Utilized cross-validation techniques to assess model performance and prevent overfitting.
- Selected the best-performing models based on evaluation metrics such as R-squared score and Mean Absolute Error.

**Streamlit App Development:**
- Leveraged Streamlit, a powerful Python library for building interactive web applications, to develop a user-friendly interface for predicting laptop prices.
- Implemented features for users to input laptop specifications and obtain real-time price predictions.
- Integrated the trained machine learning model into the Streamlit app, ensuring seamless functionality.

## Web App Link: <a href = "https://laptop-price-predictor-1.streamlit.app/" style = "color: violet">Click Here To Visit Streamlit Web App</a> 🖥️💰🔮

## GitHub Repo: <a href = "https://github.com/RobinMillford/Laptop-Price-Predictor" style = "color: cyan">Click Here To Go To GitHub Repo..</a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('/kaggle/input/laptop-specifications-and-pricing-dataset/Cleaned_dataset.xlsx')

df.head()

,Company,TypeName,OpSys,Inches,ScreenResolution,Cpu,Gpu brand,Ram,HDD,SSD,Weight,Price
0,Apple,Ultrabook,macOS,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,Intel,8GB,0,128,1.37kg,71378.6832
1,Apple,Ultrabook,macOS,13.3,1440x900,Intel Core i5 1.8GHz,Intel,8GB,0,0,1.34kg,47895.5232
2,HP,Notebook,No OS,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,Intel,8GB,0,256,1.86kg,30636.0000
3,Apple,Ultrabook,macOS,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,AMD,16GB,0,512,1.83kg,135195.3360
4,Apple,Ultrabook,macOS,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,Intel,8GB,0,256,1.37kg,96095.8080

In [3]:
df.isnull().sum()

Company             0
TypeName            0
OpSys               0
Inches              0
ScreenResolution    0
Cpu                 0
Gpu brand           0
Ram                 0
HDD                 0
SSD                 0
Weight              0
Price               0
dtype: int64

In [4]:
df.dtypes

Company              object
TypeName             object
OpSys                object
Inches              float64
ScreenResolution     object
Cpu                  object
Gpu brand            object
Ram                  object
HDD                   int64
SSD                   int64
Weight               object
Price               float64
dtype: object

In [5]:
df.duplicated().sum()

29

In [6]:
df['Ram'] = df['Ram'].str.replace('GB', '')

df['Weight'] = df['Weight'].str.replace('kg', '')

df['Ram'] = df['Ram'].astype('int32')

df['Weight'] = df['Weight'].astype('float32')

df.head()

,Company,TypeName,OpSys,Inches,ScreenResolution,Cpu,Gpu brand,Ram,HDD,SSD,Weight,Price
0,Apple,Ultrabook,macOS,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,Intel,8,0,128,1.37,71378.6832
1,Apple,Ultrabook,macOS,13.3,1440x900,Intel Core i5 1.8GHz,Intel,8,0,0,1.34,47895.5232
2,HP,Notebook,No OS,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,Intel,8,0,256,1.86,30636.0000
3,Apple,Ultrabook,macOS,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,AMD,16,0,512,1.83,135195.3360
4,Apple,Ultrabook,macOS,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,Intel,8,0,256,1.37,96095.8080

In [7]:
df['Touchscreen'] = df['ScreenResolution'].apply(lambda x: 1 if 'Touchscreen' in x else 0)
df['Ips'] = df['ScreenResolution'].apply(lambda x: 1 if 'IPS' in x else 0)

df.head()

,Company,TypeName,OpSys,Inches,ScreenResolution,Cpu,Gpu brand,Ram,HDD,SSD,Weight,Price,Touchscreen,Ips
0,Apple,Ultrabook,macOS,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,Intel,8,0,128,1.37,71378.6832,0,1
1,Apple,Ultrabook,macOS,13.3,1440x900,Intel Core i5 1.8GHz,Intel,8,0,0,1.34,47895.5232,0,0
2,HP,Notebook,No OS,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,Intel,8,0,256,1.86,30636.0000,0,0
3,Apple,Ultrabook,macOS,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,AMD,16,0,512,1.83,135195.3360,0,1
4,Apple,Ultrabook,macOS,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,Intel,8,0,256,1.37,96095.8080,0,1

In [8]:
new = df['ScreenResolution'].str.split('x', n=1, expand=True)

df['X_res'] = new[0]
df['Y_res'] = new[1]

df['X_res'] = df['X_res'].str.replace(',', '')
df['X_res'] = df['X_res'].str.findall(r'(\d+.?\d+)').apply(lambda x: x[0]).astype('int')

df['Y_res'] = df['Y_res'].astype('int')

df['ppi'] = ((df['X_res'] ** 2 + df['Y_res'] ** 2) ** 0.5) / df['Inches']
df['ppi'] = df['ppi'].astype('float')

df.drop(columns=['Inches', 'X_res', 'Y_res', 'ScreenResolution'], inplace=True)

df

,Company,TypeName,OpSys,Cpu,Gpu brand,Ram,HDD,SSD,Weight,Price,Touchscreen,Ips,ppi
0,Apple,Ultrabook,macOS,Intel Core i5 2.3GHz,Intel,8,0,128,1.37,71378.6832,0,1,226.983005
1,Apple,Ultrabook,macOS,Intel Core i5 1.8GHz,Intel,8,0,0,1.34,47895.5232,0,0,127.677940
2,HP,Notebook,No OS,Intel Core i5 7200U 2.5GHz,Intel,8,0,256,1.86,30636.0000,0,0,141.211998
3,Apple,Ultrabook,macOS,Intel Core i7 2.7GHz,AMD,16,0,512,1.83,135195.3360,0,1,220.534624
4,Apple,Ultrabook,macOS,Intel Core i5 3.1GHz,Intel,8,0,256,1.37,96095.8080,0,1,226.983005
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1297,Lenovo,2 in 1 Convertible,Windows 10,Intel Core i7 6500U 2.5GHz,Intel,4,0,128,1.80,33992.6400,1,1,157.350512
1298,Lenovo,2 in 1 Convertible,Windows 10,Intel Core i7 6500U 2.5GHz,Intel,16,0,512,1.30,79866.7200,1,1,276.053530
1299,Lenovo,Notebook,Windows 10,Intel Celeron Dual Core N3050 1.6GHz,Intel,2,0,0,1.50,12201.1200,0,0,111.935204
1300,HP,Notebook,Windows 10,Intel Core i7 6500U 2.5GHz,AMD,6,1000,0,2.19,40705.9200,0,0,100.454670
1301,Asus,Notebook,Windows 10,Intel Celeron Dual Core N3050 1.6GHz,Intel,4,500,0,2.20,19660.3200,0,0,100.454670

In [9]:
df['Cpu Name'] = df['Cpu'].apply(lambda x: " ".join(x.split()[0:3]))

def fetch_processor(cpu_name):
    if 'Intel Core i7' in cpu_name:
        return 'Intel Core i7'
    elif 'Intel Core i5' in cpu_name:
        return 'Intel Core i5'
    elif 'Intel Core i3' in cpu_name:
        return 'Intel Core i3'
    elif 'Intel' in cpu_name:
        return 'Other Intel Processor'
    elif 'AMD' in cpu_name:
        return 'AMD Processor'
    else:
        return 'Other Processor'

df['Cpu brand'] = df['Cpu Name'].apply(fetch_processor)

df.drop(columns=['Cpu', 'Cpu Name'], inplace=True)

df.head()

,Company,TypeName,OpSys,Gpu brand,Ram,HDD,SSD,Weight,Price,Touchscreen,Ips,ppi,Cpu brand
0,Apple,Ultrabook,macOS,Intel,8,0,128,1.37,71378.6832,0,1,226.983005,Intel Core i5
1,Apple,Ultrabook,macOS,Intel,8,0,0,1.34,47895.5232,0,0,127.677940,Intel Core i5
2,HP,Notebook,No OS,Intel,8,0,256,1.86,30636.0000,0,0,141.211998,Intel Core i5
3,Apple,Ultrabook,macOS,AMD,16,0,512,1.83,135195.3360,0,1,220.534624,Intel Core i7
4,Apple,Ultrabook,macOS,Intel,8,0,256,1.37,96095.8080,0,1,226.983005,Intel Core i5

In [10]:
def cat_os(inp):
    if inp in ['Windows 10', 'Windows 7', 'Windows 10 S']:
        return 'Windows'
    elif inp in ['macOS', 'Mac OS X']:
        return 'Mac'
    else:
        return 'Others/No OS/Linux'

df['os'] = df['OpSys'].apply(cat_os)

df.drop(columns=['OpSys'], inplace=True)

df.head()

,Company,TypeName,Gpu brand,Ram,HDD,SSD,Weight,Price,Touchscreen,Ips,ppi,Cpu brand,os
0,Apple,Ultrabook,Intel,8,0,128,1.37,71378.6832,0,1,226.983005,Intel Core i5,Mac
1,Apple,Ultrabook,Intel,8,0,0,1.34,47895.5232,0,0,127.677940,Intel Core i5,Mac
2,HP,Notebook,Intel,8,0,256,1.86,30636.0000,0,0,141.211998,Intel Core i5,Others/No OS/Linux
3,Apple,Ultrabook,AMD,16,0,512,1.83,135195.3360,0,1,220.534624,Intel Core i7,Mac
4,Apple,Ultrabook,Intel,8,0,256,1.37,96095.8080,0,1,226.983005,Intel Core i5,Mac

In [11]:
df.dtypes

Company         object
TypeName        object
Gpu brand       object
Ram              int32
HDD              int64
SSD              int64
Weight         float32
Price          float64
Touchscreen      int64
Ips              int64
ppi            float64
Cpu brand       object
os              object
dtype: object

In [12]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Assuming 'df' is your DataFrame with the specified columns
categorical_columns = ['Company', 'TypeName', 'Gpu brand', 'Cpu brand', 'os']
numerical_columns = ['Ram', 'HDD', 'SSD', 'Weight', 'Price', 'Touchscreen', 'Ips', 'ppi']

# Split the DataFrame into numerical and categorical parts
numerical_df = df[numerical_columns]
categorical_df = df[categorical_columns]

# Apply one-hot encoding to the categorical columns
encoder = OneHotEncoder(drop='first')
encoded_array = encoder.fit_transform(categorical_df).toarray()
encoded_df = pd.DataFrame(encoded_array, columns=encoder.get_feature_names_out(categorical_columns))

# Combine the numerical and encoded categorical DataFrames
merged_df = pd.concat([encoded_df, numerical_df], axis=1)

merged_df.head()

,Company_Apple,Company_Asus,Company_Chuwi,Company_Dell,Company_Fujitsu,Company_Google,Company_HP,Company_Huawei,Company_LG,Company_Lenovo,...,os_Others/No OS/Linux,os_Windows,Ram,HDD,SSD,Weight,Price,Touchscreen,Ips,ppi
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8,0,128,1.37,71378.6832,0,1,226.983005
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8,0,0,1.34,47895.5232,0,0,127.677940
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,8,0,256,1.86,30636.0000,0,0,141.211998
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,16,0,512,1.83,135195.3360,0,1,220.534624
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8,0,256,1.37,96095.8080,0,1,226.983005

In [13]:
from sklearn.model_selection import train_test_split
import numpy as np

X = merged_df.drop(columns=['Price'])
y = np.log(merged_df['Price'])

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.85, test_size=0.15, random_state=2)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (1106, 38)
X_test shape: (196, 38)
y_train shape: (1106,)
y_test shape: (196,)

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score, mean_absolute_error

step1 = ColumnTransformer(transformers=[
    ('encoder', OneHotEncoder(drop='first'), [0, 1, 6, 10, 11])
], remainder='passthrough')

step2 = LinearRegression()

pipe = Pipeline(steps=[
    ('preprocessor', step1),
    ('regressor', step2)
])

pipe.fit(X_train, y_train)

y_pred = pipe.predict(X_test)

score_r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("R-squared Score:", score_r2)
print("Mean Absolute Error:", mae)

R-squared Score: 0.8073277448418685
Mean Absolute Error: 0.2101782797642876

In [15]:
from sklearn.linear_model import Ridge


step1 = ColumnTransformer(transformers=[
    ('encoder', OneHotEncoder(drop='first'), [0, 1, 6, 10, 11])
], remainder='passthrough')

step2 = Ridge(alpha=10)

pipe = Pipeline(steps=[
    ('preprocessor', step1),
    ('regressor', step2)
])

pipe.fit(X_train, y_train)

y_pred = pipe.predict(X_test)

score_r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("R-squared Score:", score_r2)
print("Mean Absolute Error:", mae)

R-squared Score: 0.8127331031311806
Mean Absolute Error: 0.20926802242582998

In [16]:
from sklearn.tree import DecisionTreeRegressor

step1 = ColumnTransformer(transformers=[
    ('encoder', OneHotEncoder(drop='first'), [0, 1, 6, 10, 11])
], remainder='passthrough')

step2 = DecisionTreeRegressor(max_depth=8)

pipe = Pipeline(steps=[
    ('preprocessor', step1),
    ('regressor', step2)
])

pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)

score_r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("R-squared Score:", score_r2)
print("Mean Absolute Error:", mae)

R-squared Score: 0.8341496555748473
Mean Absolute Error: 0.1848887427733343

In [17]:
from sklearn.svm import SVR

step1 = ColumnTransformer(transformers=[
    ('encoder', OneHotEncoder(drop='first'), [0, 1, 6, 10, 11])
], remainder='passthrough')

step2 = SVR(kernel='rbf', C=10000, epsilon=0.1)

pipe = Pipeline(steps=[
    ('preprocessor', step1),
    ('regressor', step2)
])

pipe.fit(X_train, y_train)

y_pred = pipe.predict(X_test)

score_r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("R-squared Score:", score_r2)
print("Mean Absolute Error:", mae)

R-squared Score: 0.8083180902267864
Mean Absolute Error: 0.20239059427179398

In [18]:
from sklearn.ensemble import RandomForestRegressor


step1 = ColumnTransformer(transformers=[
    ('encoder', OneHotEncoder(drop='first'), [0, 1, 6, 10, 11])
], remainder='passthrough')

step2 = RandomForestRegressor(n_estimators=100, random_state=3, max_samples=0.5, max_features=0.75, max_depth=15)

pipe = Pipeline(steps=[
    ('preprocessor', step1),
    ('regressor', step2)
])

pipe.fit(X_train, y_train)

y_pred = pipe.predict(X_test)

score_r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("R-squared Score:", score_r2)
print("Mean Absolute Error:", mae)

R-squared Score: 0.8867177609501874
Mean Absolute Error: 0.1600112211254077

In [19]:
from sklearn.ensemble import GradientBoostingRegressor


step1 = ColumnTransformer(transformers=[
    ('encoder', OneHotEncoder(drop='first'), [0, 1, 6, 10, 11])
], remainder='passthrough')

step2 = GradientBoostingRegressor(n_estimators=500)

pipe = Pipeline(steps=[
    ('preprocessor', step1),
    ('regressor', step2)
])

pipe.fit(X_train, y_train)

y_pred = pipe.predict(X_test)

score_r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("R-squared Score:", score_r2)
print("Mean Absolute Error:", mae)

R-squared Score: 0.8832500844194402
Mean Absolute Error: 0.15886804948044037

In [20]:
from xgboost import XGBRegressor


step1 = ColumnTransformer(transformers=[
    ('encoder', OneHotEncoder(drop='first'), [0, 1, 6, 10, 11])
], remainder='passthrough')

step2 = XGBRegressor(n_estimators=45, max_depth=5, learning_rate=0.5)

pipe = Pipeline(steps=[
    ('preprocessor', step1),
    ('regressor', step2)
])

pipe.fit(X_train, y_train)

y_pred = pipe.predict(X_test)

score_r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("R-squared Score:", score_r2)
print("Mean Absolute Error:", mae)

R-squared Score: 0.8763979114516648
Mean Absolute Error: 0.16307857755233787

In [21]:
from sklearn.ensemble import ExtraTreesRegressor

step2 = ExtraTreesRegressor(n_estimators=100, random_state=0)

pipe = Pipeline(steps=[
    ('preprocessor', step1),
    ('regressor', step2)
])

pipe.fit(X_train, y_train)

y_pred = pipe.predict(X_test)

score_r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("ExtraTreesRegressor:")
print("R-squared Score:", score_r2)
print("Mean Absolute Error:", mae)

ExtraTreesRegressor:
R-squared Score: 0.8707894273162847
Mean Absolute Error: 0.15956027547146978

In [22]:
from sklearn.ensemble import StackingRegressor
import joblib


step1 = ColumnTransformer(transformers=[
    ('encoder', OneHotEncoder(drop='first'), [0, 1, 6, 10, 11])
], remainder='passthrough')

base_estimators = [
    ('rf', RandomForestRegressor(n_estimators=350, max_depth=15)),
    ('gb', GradientBoostingRegressor(n_estimators=100, max_features=0.5)),
    ('xgb', XGBRegressor(n_estimators=25, learning_rate=0.3, max_depth=5))
]

step2 = StackingRegressor(estimators=base_estimators, final_estimator=Ridge())

pipe = Pipeline(steps=[
    ('preprocessor', step1),
    ('regressor', step2)
])

pipe.fit(X_train, y_train)

joblib.dump(pipe, 'stacked_regression_model.pkl')

['stacked_regression_model.pkl']